### ISSUE TITLE
How fast inference on android device

### ISSUE THREAD

**Issue by kikirizki** [DaichiTakigawa/pytorch-android-ssd#1]
Thank you so much for your great works! I am wondering how fast the inference on android device? I am trying to decide to choose between MNN and PyTorch Mobile

**Comment by DaichiTakigawa** [comment]
I have tried it on only cpu, not gpu or npu, but it took about 2 second per image.

**Comment by kikirizki** [comment]
Hi, Thank you for your brief response, do you recommend pytorch mobile or Alibaba's MNN for android deployment if my consideration is only performance/inference speed?

**Comment by DaichiTakigawa** [comment]
Sorry. I'm not super familiar with making inferences on mobile devices, but I think tensorflow lite is probably the most production ready and famous.

**Comment by kikirizki** [comment]
Oh thamk you for your response, I think I can close the issue now
